modLoader="javafml"
loaderVersion="[36,)"
license="GNU GPL v3.0"
[[mods]]
modId="rotp_cr"
version="${file.jarVersion}"
displayName="Chariot Requiem RoTP Addon"
logoFile="logo.png"
credits="StandoByte, "
authors="TheDoGGy"
description='''
This is requiem... addon!
'''
[[dependencies.rotp_cr]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_cr]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
[[dependencies.rotp_cr]]
    modId="jojo"
    mandatory=true
    versionRange="[0.2.2,0.3)"
    ordering="AFTER"
    side="BOTH"
